ONSdigital/dp-search-data-importer

Makefile, config/config.go, event/consumer_test.go, features/steps/component.go, features/steps/steps.go
* update config with removing use of file
* no valid component test yet, separate card
* see code changes make sense and CI passes
* Anyone
=> config updates

event/consumer.go, service/service.go
* refactoring service run
* CI passes
* Anyone
=> refactoring service

models/elastic.go
* Handle empty release date to parse successfully
* code change make sense
* Anyone
=> Update to handle empty releasedate

handler/handler.go, handler/handler_test.go
* Fix for handling ES create 409 error
* code sense check and CI pass
* Anyone
=> Fix for handling es create error

cmd/producer/main.go, handler/handler.go, handler/handler_test.go, models/elastic.go, transform/transform.go
* removing additional uid field while preparing bulk request
* refactoring for update action
* check, by running unit test, bulk request is not having uid field
* extensive test may include running service locally and see if update action is performed for duplicate document
* CI Pass
* anyone
=> bulk request update with removing uid

event/batch.go, go.mod, go.sum
* Log Lib version update to v2.2.0
* code sense check
* anyone
=> log lib version updates

event/batch.go, event/batch_test.go, event/consumer.go
* Refactoring updates for including traceId into the context details
* code sense check
* CI Pass
* anyone
=> Refactoring updates for traceid into context

event/consumer.go
**Describe what you have changed and why.**
- Remove `trace_id` from `log.Data` as it is already available in `Context`
**Describe the steps required to test the changes.**
- Check if the code changes make sense
**Describe who worked on the changes, so that other people can review.**
- Anyone
=> remove `trace_id` from `log.Data`

models/elastic.go, models/event.go, schema/schema.go, transform/transform.go
Add uri attribute to search data import model
This is tested against the dp search bulk indexing script in develop.
=> Add uri attribute to models

handler/handler_test.go, models/elastic.go, models/event.go, schema/schema.go, transform/transform.go
Add missing survey and language fields for release calender.
Check if the changes makes sense. 
=> Add missing survey and language fields for rc

handler/handler_test.go, models/elastic.go, models/event.go, schema/schema.go, transform/transform.go
This pr contains the following: 
-  Add ```canonicalTopic``` extra field
Please see if the changes make sense. 
=> Add canonicalTopic fields to the release calender

go.mod, go.sum, handler/handler.go, handler/handler_test.go, service/initialise.go, service/interfaces.go, service/mock/healthCheck.go, service/mock/initialiser.go, service/mock/server.go, service/service.go, service/service_test.go
This pr attempts to update the dp-elasticsearch library to the latest version and also point the dp search data importer to new version of elasticsearch 7.10
Check if the changes make sense. 
=> Use new version of elasticsearch library

models/elastic.go, models/event.go, schema/schema.go, transform/transform.go
This pr just adds edition field to both event and es model. 
Please see if the changes make sense
=> Add edition field for both event and elastic model

Dockerfile.concourse, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml, go.mod
As per title
Check container image is available.
Anyone
=> Update container base to Ubuntu 20.04, update go to v19

features/import-search-data.feature, models/elastic.go, models/event.go, schema/schema.go, transform/transform.go
[Trello card](https://trello.com/c/bMrLzffC/1313-1313-de-duplicate-population-type-dimensions-in-search-extractor)
- Add key to the event model and schema
- Map the new field and store it to elasticsearch
- Make sure code changes make sense
- Make sure tests pass, and cover the new functionality
Anyone
=> store new label-based key in elasticsearch

.golangci.yml, Makefile, README.md, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml, features/steps/assertor.go, features/steps/steps.go, handler/handler.go, handler/handler_test.go, service/service_test.go
Update README.md to include link to documentation of search application architecture. Also includes:
update Makefile targets, incl. new help target
update ci image used for linting
Sanity check changes
Anyone
=> Update documentation - link off to search architecture

ci/build.yml, ci/component.yml, ci/unit.yml
Specify bullseye for CI images to fix pipeline. 
Check ok. 
Not me.
=> Set bullseye for ci images

Dockerfile.local
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
=> bump dockerfile.local to go1.22

dp-search-data-importer.nomad
As per title.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
=> Ensure deployments spread over availability zones

Dockerfile.concourse
Release branch containing…
- [upgrade to ubuntu22.4 for base docker image](https://github.com/ONSdigital/dp-search-data-importer/commit/78a6a08ee947a649431208be239c59a0bedf21f1)
Ensure only expected commits and tests pass.
Anyone
=> Release 1.4.0

features/search-content-deleted.feature, features/steps/steps.go, handler/handler.go, handler/handler_test.go
switch delete impl to bulkupdate
Sense check
!me
=> switch delete impl to bulkupdate

models/event.go, schema/schema.go
Ensure schema and model consistency
Sense check
Ensure tests pass
!me
=> ensure schema and model consistency
